name: chick_game_prototype
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_riverpod: ^3.0.3
  shared_preferences: ^2.5.3
  google_fonts: ^6.3.2
  path_provider: ^2.1.5
  image_picker: ^1.2.1
  intl: ^0.20.2
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

dependency_overrides:
  audioplayers_darwin:
    path: third_party/audioplayers_darwin

flutter:
  uses-material-design: true

  assets:
    - assets/lvls_webp/
    - assets/btn_webp/
    - assets/score_webp/
    - assets/background_webp/
    - assets/chick_webp/
    - assets/profile_webp/
    - assets/info_webp/
    - assets/eggs/
    - assets/sounds/

  fonts:
    - family: Rubik Mono One
      fonts:
        - asset: assets/fonts/RubikMonoOne-Regular.ttf
